pool:
  vmImage: 'vs2017-win2016'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: npm install
  workingDirectory: './Site'
  name: 'install'
- script: npm run build
  workingDirectory: './Site'
  name: 'build'

- task: CopyFiles@2
  displayName: Copy site
  inputs:
    SourceFolder: ./Site/public/
    TargetFolder: '$(Build.ArtifactStagingDirectory)/public'

- task: PublishBuildArtifacts@1
  displayName: Pubish artifacts
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/public'
    artifactName: web