variables:
  acr: ytnetworks.azurecr.io
  image: ytnetworks

jobs:


- job: Docker
  pool:
    vmImage: ubuntu-latest

  steps:
  - task: Docker@1
    displayName: Login
    inputs:
      azureSubscriptionEndpoint: Mark Ledwich ARM
      azureContainerRegistry: $(acr)
      command: login

  - task: Docker@1
    displayName: Build YtCli
    inputs:
      command: Build an image
      imageName: $(acr)/$(image):latest

  - task: Docker@1
    displayName: Push YtCli
    inputs:
      command: Push an image
      imageName: $(acr)/$(image):latest

- job: App
  pool:
    vmImage: windows-latest

  steps:
  - script: dotnet publish -c Release --output $(Build.ArtifactStagingDirectory)/YtFunctions
    workingDirectory: ./App/YtFunctions
    displayName: Publish YtFunctions

  # - task: DotNetCoreCLI@2
  #   displayName: Build YtFunctions
  #   inputs:
  #     command: publish
  #     publishWebProjects: false
  #     workingDirectory: ./App/YtFunctions
  #     zipAfterPublish: false
  #     verbosityPack: Normal
  #     verbosityRestore: Normal
  #     outputDir: $(Build.ArtifactStagingDirectory)/YtFunctions

  - task: PublishBuildArtifacts@1
    displayName: Pubish YtFunctions Artifact
    inputs:
        pathtoPublish: $(Build.ArtifactStagingDirectory)/YtFunctions
        artifactName: YtFunctions

- job: Site
  pool:
    vmImage: vs2017-win2016
    
  steps:

    - script: npm install
      displayName: npm install
      workingDirectory: ./Site

    - script: npm run build
      displayName: npm build
      workingDirectory: ./Site

    - task: CopyFiles@2
      displayName: Copy site
      inputs:
          SourceFolder: ./Site/public/
          TargetFolder: $(Build.ArtifactStagingDirectory)/public

    - task: PublishBuildArtifacts@1
      displayName: Pubish artifacts
      inputs:
          pathtoPublish: $(Build.ArtifactStagingDirectory)/public
          artifactName: web