jobs:

- job: App
  pool:
    vmImage: vs2017-win2016

  steps:

  - task: Docker@1
    displayName: Build YtCli Image
    inputs:
      imageName: ytnetworks.azurecr.io/ytnetworks:$(Build.BuildId)

  - task: Docker@1
    displayName: Login
    inputs:
      azureSubscriptionEndpoint: Mark Ledwich ARM
      azureContainerRegistry: ytnetworks.azurecr.io
      command: login

  - task: Docker@1
    displayName: Push YtCli Image
    inputs:
      command: Push an image
      imageName: ytnetworks.azurecr.io/ytnetworks:$(Build.BuildId)

  - task: DotNetCoreCLI@2
    displayName: Build YtFunctions
    inputs:
      command: publish
      zipAfterPublish: true
      workingDirectory: ./Crawler/YtFunctions

  - task: PublishBuildArtifacts@1
    displayName: Pubish artifacts
    inputs:
        pathtoPublish: $(Build.ArtifactStagingDirectory)/YtFunctions
        artifactName: YtFunctions

- job: Site
  pool:
    vmImage: 'vs2017-win2016'
    
  steps:

    - script: npm install
      displayName: npm install
      workingDirectory: ./Site

    - script: npm run build
      displayName: npm build
      workingDirectory: ./Site

    - task: CopyFiles@2
      displayName: Copy site
      inputs:
          SourceFolder: ./Site/public/
          TargetFolder: $(Build.ArtifactStagingDirectory)/public

    - task: PublishBuildArtifacts@1
      displayName: Pubish artifacts
      inputs:
          pathtoPublish: $(Build.ArtifactStagingDirectory)/public
          artifactName: web